update ci.yml

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -568,15 +568,15 @@ jobs:
   # ============================================================================
 
   pr-preview:
-    name: PR Preview Build
+    name: Creator Hub Build
     strategy:
+      fail-fast: true
       matrix:
         os: [ macos-latest, windows-latest ]
     runs-on: ${{ matrix.os }}
-    needs: [ build ]
-    if: github.event_name == 'pull_request'
     env:
       WORKING_DIRECTORY: packages/@dcl/creator-hub
+
     steps:
       - uses: actions/checkout@v4
         with:
@@ -588,31 +588,26 @@ jobs:
           node-version: 22
           cache: 'npm'
 
-      - name: Install @dcl/inspector@branch package
-        run: npm install "${{ secrets.SDK_TEAM_S3_BASE_URL }}/${{ needs.build.outputs.decentraland_inspector_s3_bucket_key }}"
+      - name: 'Install dependencies'
+        run: npm ci
         working-directory: ${{ env.WORKING_DIRECTORY }}
         env:
           PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
 
-      - name: Install dependencies
-        run: npm i --silent
-        working-directory: ${{ env.WORKING_DIRECTORY }}
-        env:
-          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
-
-      - name: Build application (development mode)
-        run: echo MODE=development && npm run build
+      - name: 'Build'
+        run: echo MODE=$MODE && npm run build
         working-directory: ${{ env.WORKING_DIRECTORY }}
         env:
           NODE_OPTIONS: "--max-old-space-size=8192"
-          MODE: development
+          MODE: ${{ !github.event.pull_request.number && 'production' || 'development' }}
           VITE_SEGMENT_CREATORS_HUB_API_KEY: ${{ secrets.VITE_SEGMENT_CREATORS_HUB_API_KEY }}
           VITE_SEGMENT_INSPECTOR_API_KEY: ${{ secrets.VITE_SEGMENT_INSPECTOR_API_KEY }}
           VITE_ALLOWED_EXTERNAL_ORIGINS: ${{ secrets.VITE_ALLOWED_EXTERNAL_ORIGINS }}
+          # Sentry AUTH Token
           SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
           VITE_SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
 
-      - name: Generate preview version
+      - name: Generate release version
         id: version
         uses: paulhatch/semantic-version@v5.4.0
         with:
@@ -624,47 +619,97 @@ jobs:
           bump_each_commit_patch_pattern: "/^(patch|fix).+/"
           search_commit_body: true
           user_format_type: "json"
+          change_path: ${{ env.WORKING_DIRECTORY }}
 
-      - name: Build artifacts (no publishing)
-        run: npx electron-builder --config electron-builder.cjs --config.extraMetadata.version=${{ steps.version.outputs.version }} --publish never
-        working-directory: ${{ env.WORKING_DIRECTORY }}
+      # Download 'SSLcom/esigner-codesign' to a folder called 'esigner-codesign' inside creator-hub package
+      - name: Checkout esigner-codesign repository (Windows)
+        if: ${{github.ref == 'refs/heads/main' && matrix.os == 'windows-latest' && !github.event.pull_request.number}}
+        uses: actions/checkout@v3
+        with:
+          repository: 'SSLcom/esigner-codesign'
+          path: ${{ env.WORKING_DIRECTORY }}/esigner-codesign
+
+      - name: Compile artifacts ${{ github.event.pull_request.number && ' ' || 'and upload them to github release' }}
+        # I use this action because it is capable of retrying multiple times if there are any issues with the distribution server
+        uses: nick-fields/retry@v3
+        with:
+          timeout_minutes: 60
+          max_attempts: 6
+          retry_wait_seconds: 15
+          retry_on: error
+          shell: 'bash'
+          command: cd ${{ env.WORKING_DIRECTORY }} && npx electron-builder --config electron-builder.cjs --config.extraMetadata.version=${{ steps.version.outputs.version }} ${{ matrix.os == 'macos-latest' && format('--config.mac.notarize={0}', true) || '' }} --publish ${{ github.event.pull_request.number && 'never' || 'always' }}
         env:
+          # Disable hard links to avoid issues with npm
           USE_HARD_LINKS: false
+          # Code Signing params
+          # See https://www.electron.build/code-signing
+          CSC_LINK: ${{ secrets.MACOS_CSC_LINK }}
+          CSC_KEY_PASSWORD: ${{ secrets.MACOS_CSC_KEY_PASSWORD }}
+          # Notarization params
+          # See https://www.electron.build/configuration/mac#NotarizeNotaryOptions
+          APPLE_ID: ${{ secrets.MACOS_NOTARIZATION_APPLE_ID }}
+          APPLE_TEAM_ID: ${{ secrets.MACOS_NOTARIZATION_TEAM_ID }}
+          APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.MACOS_NOTARIZATION_PWD }}
+          # Publishing artifacts
+          GH_TOKEN: ${{ secrets.github_token }} # GitHub token, automatically provided (No need to define this secret in the repo settings)
+          EP_PRE_RELEASE: true # Publish as pre-release
+          # The following are the parameters required by the esigner-codesign action to work, we must explicitly pass in even the optional ones since we're not using the action directly, but from the checked out repo
+          CODE_SIGN_SCRIPT_PATH: ${{ matrix.os == 'windows-latest' && format('{0}\\esigner-codesign\\dist\\index.js', github.workspace) || '' }}
+          INPUT_COMMAND: "sign"
+          INPUT_FILE_PATH: "${{ github.workspace }}\\dist\\Decentraland Creator Hub-${{ steps.version.outputs.version }}-win-x64.exe"
+          INPUT_OVERRIDE: "true"
+          INPUT_MALWARE_BLOCK: "false"
+          INPUT_CLEAN_LOGS: "false"
+          INPUT_JVM_MAX_MEMORY: "1024M"
+          INPUT_ENVIRONMENT_NAME: "PROD"
+          INPUT_USERNAME: ${{ secrets.ES_USERNAME }}
+          INPUT_PASSWORD: ${{ secrets.ES_PASSWORD }}
+          INPUT_TOTP_SECRET: ${{ secrets.ES_TOTP_SECRET }}
+          INPUT_CREDENTIAL_ID: ${{ secrets.WINDOWS_CREDENTIAL_ID_SIGNER }}
 
       - name: Move artifacts to upload folder
-        run: sh -c 'mkdir dist/upload && cp dist/*.dmg dist/*.exe dist/upload 2> /dev/null || :'
+        if: ${{ github.event.pull_request.number }}
         working-directory: ${{ env.WORKING_DIRECTORY }}
+        run: sh -c 'mkdir dist/upload && cp dist/*.dmg dist/*.exe dist/upload 2> /dev/null || :'
 
       - name: Upload to S3
+        if: ${{ github.event.pull_request.number }}
         id: upload
+        working-directory: ${{ env.WORKING_DIRECTORY }}
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.SDK_TEAM_AWS_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.SDK_TEAM_AWS_SECRET }}
         run: |
-          npx @dcl/cdn-uploader@next --bucket "${{ secrets.SDK_TEAM_S3_BUCKET }}" --local-folder "dist/upload" --bucket-folder "creator-hub/branch/${{ github.head_ref }}"
+          npx @dcl/cdn-uploader@next \
+            --bucket ${{ secrets.SDK_TEAM_S3_BUCKET }} \
+            --local-folder dist/upload \
+            --bucket-folder creator-hub/branch/${{ github.head_ref }}
 
       - name: Set specific windows instructions
         if: ${{ github.event.pull_request.number && matrix.os == 'windows-latest' }}
         id: windows-instructions
+        working-directory: ${{ env.WORKING_DIRECTORY }}
         run: |
           echo "list<<EOF" >> $GITHUB_ENV
           echo "[win-x64](${{ secrets.SDK_TEAM_S3_BASE_URL }}/creator-hub/branch/${{ github.head_ref }}/Decentraland%20Creator%20Hub-${{ steps.version.outputs.version }}-win-x64.exe)" >> $GITHUB_ENV
           echo "EOF" >> $GITHUB_ENV
 
-      - name: Set download instructions (macOS)
+      - name: Set specific macos instructions
         if: ${{ github.event.pull_request.number && matrix.os == 'macos-latest' }}
         id: macos-instructions
+        working-directory: ${{ env.WORKING_DIRECTORY }}
         run: |
           echo "list<<EOF" >> $GITHUB_ENV
           echo "[mac-x64](${{ secrets.SDK_TEAM_S3_BASE_URL }}/creator-hub/branch/${{ github.head_ref }}/Decentraland%20Creator%20Hub-${{ steps.version.outputs.version }}-mac-x64.dmg)" >> $GITHUB_ENV
           echo "[mac-arm64](${{ secrets.SDK_TEAM_S3_BASE_URL }}/creator-hub/branch/${{ github.head_ref }}/Decentraland%20Creator%20Hub-${{ steps.version.outputs.version }}-mac-arm64.dmg)" >> $GITHUB_ENV
           echo "EOF" >> $GITHUB_ENV
-          content=$(cat ./.github/workflows/creator-hub-macos-instructions.md)
+          content=$(cat ./.github/workflows/macos-instructions.md)
           echo "macos-instructions<<EOF" >> $GITHUB_ENV
           echo "$content" >> $GITHUB_ENV
           echo "EOF" >> $GITHUB_ENV
 
-      - name: Find existing comment
+      - name: Find Comment
         if: ${{ github.event.pull_request.number }}
         uses: peter-evans/find-comment@v1
         id: fc
